version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    labels: []
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 750
    target-branch: REL1_39
